version: 0.1.{build}

image: Visual Studio 2015

environment:
  matrix:
    - CONDA_INSTALL_LOCN: C:\Miniconda36-x64
      TARGET_ARCH: x64
      ARCH: 64
      GENERATOR: Visual Studio 14 2015 Win64

platform:
  - x64

install:
  - cmd: rmdir C:\cygwin /s /q
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda.exe update --yes --quiet conda
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda.exe install conda-build --yes
  - cmd: conda.exe config --set show_channel_urls true
  - cmd: conda.exe config --remove channels defaults
  - cmd: conda.exe config --add channels defaults
  - cmd: conda.exe config --add channels conda-forge

build: off

test_script:
  - cmd: conda.exe build .ci\conda
  - cmd: mkdir dist
  - cmd: copy %CONDA_INSTALL_LOCN%\conda-bld\win-%ARCH%\*.bz2 dist

artifacts:
- path: dist\*
