//
// /Users/yixinhu/CLionProjects/TetWild/ispc/energy.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC__USERS_YIXINHU_CLIONPROJECTS_TETWILD_ISPC_ENERGY_H
#define ISPC__USERS_YIXINHU_CLIONPROJECTS_TETWILD_ISPC_ENERGY_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

#ifndef __ISPC_ALIGN__
#if defined(__clang__) || !defined(_MSC_VER)
// Clang, GCC, ICC
#define __ISPC_ALIGN__(s) __attribute__((aligned(s)))
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Visual Studio
#define __ISPC_ALIGN__(s) __declspec(align(s))
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void energy_ispc(double * V1_x, double * V1_y, double * V1_z, double * V2_x, double * V2_y, double * V2_z, double * V3_x, double * V3_y, double * V3_z, double * V4_x, double * V4_y, double * V4_z, double * E, int32_t count);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC__USERS_YIXINHU_CLIONPROJECTS_TETWILD_ISPC_ENERGY_H
